#!/usr/bin/env python3
"""
repeated_runs_similarity.py

Computes within-dialect vs between-dialect similarity across 5 repeated runs
of the base gpt-4.1 model (no system prompt) on the 15 Round 1 prompts.

Two independent measures are computed side by side:
  Cosine similarity  — semantic similarity via text-embedding-3-large
  Jaccard similarity — lexical overlap (token-level and bigram-level)

Having both matters: if within-dialect > between-dialect on BOTH measures,
you have two independent lines of evidence that the gap is caused by dialect
and not by the embedding model or temperature variation.

Measurements per prompt (for each metric):
  within_sae      — mean over all pairs of SAE trials (10 pairs for 5 trials)
  within_aave     — mean over all pairs of AAVE trials
  between_matched — SAE trial k vs AAVE trial k (5 matched pairs)
  between_all     — every SAE trial vs every AAVE trial (25 pairs)

Key number: dialect gap = within_sae - between_matched
  > 0.05 on cosine  → dialect effect exceeds temperature noise
  > 0.03 on token J → lexically confirmed (embedding-independent)

Reads from:
    Final_Dataset/study_logs/round1_repeated_runs.jsonl
    (generated by collect_round1_repeated_runs.py)

Output:
    Final_Dataset/round1_repeated_runs_similarity.xlsx
    Printed tables to stdout

Usage:
    export OPENAI_API_KEY="your-key"
    python scripts/repeated_runs_similarity.py
"""

from __future__ import annotations

import itertools
import json
import math
import os
import random
import re
import statistics
from collections import defaultdict
from pathlib import Path

from openai import OpenAI
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

REPO_ROOT   = Path(__file__).resolve().parent.parent
DATA_PATH   = REPO_ROOT / "Final_Dataset" / "study_logs" / "round1_repeated_runs.jsonl"
OUTPUT_PATH = REPO_ROOT / "Final_Dataset" / "round1_repeated_runs_similarity.xlsx"
EMBED_MODEL = "text-embedding-3-large"
BATCH_SIZE  = 64


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_records(path: Path) -> list[dict]:
    records = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            if r.get("record_type") != "trial_result":
                continue
            if r.get("status") != "success":
                continue
            text = (r.get("response_text") or "").strip()
            if not text:
                continue
            records.append({
                "trial":         r["trial"],
                "prompt_index":  r["prompt_index"],
                "category":      r.get("category", ""),
                "dialect":       r["dialect"],
                "response_text": text,
            })
    return records


# ---------------------------------------------------------------------------
# Cosine similarity
# ---------------------------------------------------------------------------

def batched(items: list, size: int) -> list[list]:
    return [items[i : i + size] for i in range(0, len(items), size)]


def get_embeddings(client: OpenAI, texts: list[str]) -> list[list[float]]:
    vectors: list[list[float]] = []
    for batch in batched(texts, BATCH_SIZE):
        resp = client.embeddings.create(model=EMBED_MODEL, input=batch)
        vectors.extend(row.embedding for row in resp.data)
    return vectors


def cosine(a: list[float], b: list[float]) -> float:
    dot    = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


# ---------------------------------------------------------------------------
# Jaccard similarity
# ---------------------------------------------------------------------------

def tokenize(text: str) -> list[str]:
    return [t for t in re.sub(r"[^a-z0-9\s]", " ", text.lower()).split() if t]


def bigrams(tokens: list[str]) -> list[tuple[str, str]]:
    return [(tokens[i], tokens[i + 1]) for i in range(len(tokens) - 1)]


def jaccard(a: set, b: set) -> float:
    if not a and not b:
        return 1.0
    union = a | b
    return len(a & b) / len(union) if union else 0.0


def jaccard_token(r1: dict, r2: dict) -> float:
    return jaccard(set(r1["tokens"]), set(r2["tokens"]))


def jaccard_bigram(r1: dict, r2: dict) -> float:
    return jaccard(set(r1["bigrams"]), set(r2["bigrams"]))


def attach_jaccard_fields(records: list[dict]) -> None:
    for r in records:
        toks = tokenize(r["response_text"])
        r["tokens"] = toks
        r["bigrams"] = bigrams(toks)


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

def mean_or_none(vals: list[float]) -> float | None:
    return statistics.mean(vals) if vals else None


def analyse(records: list[dict]) -> list[dict]:
    grouped: dict[int, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for r in records:
        grouped[r["prompt_index"]][r["dialect"]].append(r)

    prompt_rows = []
    for prompt_index in sorted(grouped):
        sae_runs  = sorted(grouped[prompt_index].get("SAE",  []), key=lambda x: x["trial"])
        aave_runs = sorted(grouped[prompt_index].get("AAVE", []), key=lambda x: x["trial"])
        category  = (sae_runs or aave_runs)[0]["category"]

        cos_within_sae:  list[float] = []
        cos_within_aave: list[float] = []
        cos_betw_match:  list[float] = []
        cos_betw_all:    list[float] = []

        tok_within_sae:  list[float] = []
        tok_within_aave: list[float] = []
        tok_betw_match:  list[float] = []
        tok_betw_all:    list[float] = []

        bi_within_sae:   list[float] = []
        bi_within_aave:  list[float] = []
        bi_betw_match:   list[float] = []
        bi_betw_all:     list[float] = []

        for l, r in itertools.combinations(sae_runs, 2):
            cos_within_sae.append(cosine(l["embedding"], r["embedding"]))
            tok_within_sae.append(jaccard_token(l, r))
            bi_within_sae.append(jaccard_bigram(l, r))

        for l, r in itertools.combinations(aave_runs, 2):
            cos_within_aave.append(cosine(l["embedding"], r["embedding"]))
            tok_within_aave.append(jaccard_token(l, r))
            bi_within_aave.append(jaccard_bigram(l, r))

        aave_by_trial = {r["trial"]: r for r in aave_runs}
        for sae_r in sae_runs:
            aave_r = aave_by_trial.get(sae_r["trial"])
            if aave_r:
                cos_betw_match.append(cosine(sae_r["embedding"], aave_r["embedding"]))
                tok_betw_match.append(jaccard_token(sae_r, aave_r))
                bi_betw_match.append(jaccard_bigram(sae_r, aave_r))

        for sae_r in sae_runs:
            for aave_r in aave_runs:
                cos_betw_all.append(cosine(sae_r["embedding"], aave_r["embedding"]))
                tok_betw_all.append(jaccard_token(sae_r, aave_r))
                bi_betw_all.append(jaccard_bigram(sae_r, aave_r))

        prompt_rows.append({
            "prompt_index":      prompt_index,
            "category":          category,
            "n_sae_trials":      len(sae_runs),
            "n_aave_trials":     len(aave_runs),
            # cosine — per-prompt means and raw lists for pooled t-test
            "cos_within_sae":    mean_or_none(cos_within_sae),
            "cos_within_aave":   mean_or_none(cos_within_aave),
            "cos_betw_match":    mean_or_none(cos_betw_match),
            "cos_betw_all":      mean_or_none(cos_betw_all),
            "_cos_within_sae":   cos_within_sae,
            "_cos_betw_match":   cos_betw_match,
            # token jaccard
            "tok_within_sae":    mean_or_none(tok_within_sae),
            "tok_within_aave":   mean_or_none(tok_within_aave),
            "tok_betw_match":    mean_or_none(tok_betw_match),
            "tok_betw_all":      mean_or_none(tok_betw_all),
            "_tok_within_sae":   tok_within_sae,
            "_tok_betw_match":   tok_betw_match,
            # bigram jaccard
            "bi_within_sae":     mean_or_none(bi_within_sae),
            "bi_within_aave":    mean_or_none(bi_within_aave),
            "bi_betw_match":     mean_or_none(bi_betw_match),
            "bi_betw_all":       mean_or_none(bi_betw_all),
            "_bi_within_sae":    bi_within_sae,
            "_bi_betw_match":    bi_betw_match,
        })
    return prompt_rows


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def build_category_rows(prompt_rows: list[dict]) -> list[dict]:
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for r in prompt_rows:
        by_cat[r["category"]].append(r)

    rows = []
    for cat in sorted(by_cat):
        group = by_cat[cat]

        def cm(key):
            vals = [r[key] for r in group if r[key] is not None]
            return statistics.mean(vals) if vals else None

        rows.append({
            "category":        cat,
            "n":               len(group),
            "cos_within_sae":  cm("cos_within_sae"),
            "cos_within_aave": cm("cos_within_aave"),
            "cos_betw_match":  cm("cos_betw_match"),
            "cos_betw_all":    cm("cos_betw_all"),
            "tok_within_sae":  cm("tok_within_sae"),
            "tok_within_aave": cm("tok_within_aave"),
            "tok_betw_match":  cm("tok_betw_match"),
            "tok_betw_all":    cm("tok_betw_all"),
            "bi_within_sae":   cm("bi_within_sae"),
            "bi_within_aave":  cm("bi_within_aave"),
            "bi_betw_match":   cm("bi_betw_match"),
            "bi_betw_all":     cm("bi_betw_all"),
        })
    return rows


N_PERMUTATIONS = 5000
RNG_SEED       = 42


def permutation_test(within: list[float], between: list[float]) -> tuple[float, float] | tuple[None, None]:
    """
    One-sided permutation test: is the observed gap (mean_within - mean_between)
    larger than would be expected by chance?

    How it works:
      1. Compute the real observed gap: mean(within) - mean(between).
      2. Pool all scores together into one combined list.
      3. Randomly shuffle the pool 5,000 times. Each shuffle, split the pool
         back into two groups of the original sizes and compute the gap.
      4. The p-value is the fraction of shuffles that produced a gap >= the
         real observed gap. A small p-value means the real gap is unlikely
         under the null hypothesis that both groups are drawn from the same
         distribution — i.e., dialect is actually driving the difference.

    Why not enumerate all permutations?
      With ~150 within-scores and ~75 between-scores, the number of ways to
      partition 225 items into groups of those sizes is ~10^63 — impossible to
      enumerate. 5,000 random samples give a reliable estimate of the p-value.

    Returns (observed_gap, p_value).
    """
    if len(within) < 2 or len(between) < 2:
        return None, None

    observed_gap = statistics.mean(within) - statistics.mean(between)
    n_within     = len(within)
    combined     = within + between

    rng   = random.Random(RNG_SEED)
    count = 0
    for _ in range(N_PERMUTATIONS):
        rng.shuffle(combined)
        perm_gap = statistics.mean(combined[:n_within]) - statistics.mean(combined[n_within:])
        if perm_gap >= observed_gap:
            count += 1

    p_value = (count + 1) / (N_PERMUTATIONS + 1)
    return round(observed_gap, 4), round(p_value, 6)


def build_summary(prompt_rows: list[dict]) -> dict:
    def om(key):
        vals = [r[key] for r in prompt_rows if r[key] is not None]
        return statistics.mean(vals) if vals else None

    # Pool all pairwise scores across prompts for the t-tests
    all_cos_within = [s for r in prompt_rows for s in r["_cos_within_sae"]]
    all_cos_betw   = [s for r in prompt_rows for s in r["_cos_betw_match"]]
    all_tok_within = [s for r in prompt_rows for s in r["_tok_within_sae"]]
    all_tok_betw   = [s for r in prompt_rows for s in r["_tok_betw_match"]]
    all_bi_within  = [s for r in prompt_rows for s in r["_bi_within_sae"]]
    all_bi_betw    = [s for r in prompt_rows for s in r["_bi_betw_match"]]

    print("Running permutation tests (5,000 shuffles each)...")
    cos_gap, cos_p = permutation_test(all_cos_within, all_cos_betw)
    tok_gap, tok_p = permutation_test(all_tok_within, all_tok_betw)
    bi_gap,  bi_p  = permutation_test(all_bi_within,  all_bi_betw)

    return {
        "n_prompts":        len(prompt_rows),
        "n_trials":         max((r["n_sae_trials"] for r in prompt_rows), default=0),
        "n_within_pairs":   len(all_cos_within),
        "n_between_pairs":  len(all_cos_betw),
        "n_permutations":   N_PERMUTATIONS,
        "cos_within_sae":   om("cos_within_sae"),
        "cos_within_aave":  om("cos_within_aave"),
        "cos_betw_match":   om("cos_betw_match"),
        "cos_betw_all":     om("cos_betw_all"),
        "cos_gap":          cos_gap,
        "cos_p":            cos_p,
        "tok_within_sae":   om("tok_within_sae"),
        "tok_within_aave":  om("tok_within_aave"),
        "tok_betw_match":   om("tok_betw_match"),
        "tok_betw_all":     om("tok_betw_all"),
        "tok_gap":          tok_gap,
        "tok_p":            tok_p,
        "bi_within_sae":    om("bi_within_sae"),
        "bi_within_aave":   om("bi_within_aave"),
        "bi_betw_match":    om("bi_betw_match"),
        "bi_betw_all":      om("bi_betw_all"),
        "bi_gap":           bi_gap,
        "bi_p":             bi_p,
    }


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def fmt(v: float | None) -> str:
    return "n/a" if v is None else f"{v:.4f}"


def print_table(headers: list[str], rows: list[list], col_widths: list[int]) -> None:
    sep = "+" + "+".join("-" * (w + 2) for w in col_widths) + "+"
    def row_line(cells):
        parts = [f" {str(cell):<{w}} " for cell, w in zip(cells, col_widths)]
        return "|" + "|".join(parts) + "|"
    print(sep)
    print(row_line(headers))
    print(sep)
    for row in rows:
        print(row_line(row))
    print(sep)


# ---------------------------------------------------------------------------
# Excel writer
# ---------------------------------------------------------------------------

HEADER_FILL  = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT  = Font(bold=True, color="FFFFFF")
SECTION_FILL = PatternFill("solid", fgColor="D6E4F0")
SECTION_FONT = Font(bold=True)
CENTER       = Alignment(horizontal="center")


def style_header(cell) -> None:
    cell.fill = HEADER_FILL
    cell.font = HEADER_FONT
    cell.alignment = CENTER


def auto_width(ws) -> None:
    for col in ws.columns:
        max_len = max((len(str(c.value)) for c in col if c.value is not None), default=8)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 44)


def _round(v):
    return round(v, 4) if v is not None else "n/a"


def write_xlsx(path: Path, prompt_rows: list[dict], category_rows: list[dict], summary: dict) -> None:
    wb = Workbook()

    # ── Sheet 1: Per Prompt — Cosine ─────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Per Prompt (Cosine)"
    h1 = ["Prompt ID", "Category", "Within SAE", "Within AAVE",
          "Between (Matched)", "Between (All Pairs)"]
    for col, h in enumerate(h1, start=1):
        style_header(ws1.cell(1, col, h))
    for r, row in enumerate(prompt_rows, start=2):
        ws1.cell(r, 1, row["prompt_index"])
        ws1.cell(r, 2, row["category"])
        ws1.cell(r, 3, _round(row["cos_within_sae"]))
        ws1.cell(r, 4, _round(row["cos_within_aave"]))
        ws1.cell(r, 5, _round(row["cos_betw_match"]))
        ws1.cell(r, 6, _round(row["cos_betw_all"]))
    auto_width(ws1)

    # ── Sheet 2: Per Prompt — Jaccard ────────────────────────────────────
    ws2 = wb.create_sheet("Per Prompt (Jaccard)")
    h2 = ["Prompt ID", "Category",
          "Within SAE (Token)", "Within AAVE (Token)", "Between Match (Token)", "Between All (Token)",
          "Within SAE (Bigram)", "Within AAVE (Bigram)", "Between Match (Bigram)", "Between All (Bigram)"]
    for col, h in enumerate(h2, start=1):
        style_header(ws2.cell(1, col, h))
    for r, row in enumerate(prompt_rows, start=2):
        ws2.cell(r, 1, row["prompt_index"])
        ws2.cell(r, 2, row["category"])
        ws2.cell(r, 3, _round(row["tok_within_sae"]))
        ws2.cell(r, 4, _round(row["tok_within_aave"]))
        ws2.cell(r, 5, _round(row["tok_betw_match"]))
        ws2.cell(r, 6, _round(row["tok_betw_all"]))
        ws2.cell(r, 7, _round(row["bi_within_sae"]))
        ws2.cell(r, 8, _round(row["bi_within_aave"]))
        ws2.cell(r, 9, _round(row["bi_betw_match"]))
        ws2.cell(r, 10, _round(row["bi_betw_all"]))
    auto_width(ws2)

    # ── Sheet 3: By Category ─────────────────────────────────────────────
    ws3 = wb.create_sheet("By Category")
    h3 = ["Category", "n",
          "Cos Within SAE", "Cos Within AAVE", "Cos Betw Match", "Cos Betw All",
          "Tok Within SAE", "Tok Within AAVE", "Tok Betw Match", "Tok Betw All",
          "Bi Within SAE",  "Bi Within AAVE",  "Bi Betw Match",  "Bi Betw All"]
    for col, h in enumerate(h3, start=1):
        style_header(ws3.cell(1, col, h))
    for r, row in enumerate(category_rows, start=2):
        ws3.cell(r,  1, row["category"])
        ws3.cell(r,  2, row["n"])
        ws3.cell(r,  3, _round(row["cos_within_sae"]))
        ws3.cell(r,  4, _round(row["cos_within_aave"]))
        ws3.cell(r,  5, _round(row["cos_betw_match"]))
        ws3.cell(r,  6, _round(row["cos_betw_all"]))
        ws3.cell(r,  7, _round(row["tok_within_sae"]))
        ws3.cell(r,  8, _round(row["tok_within_aave"]))
        ws3.cell(r,  9, _round(row["tok_betw_match"]))
        ws3.cell(r, 10, _round(row["tok_betw_all"]))
        ws3.cell(r, 11, _round(row["bi_within_sae"]))
        ws3.cell(r, 12, _round(row["bi_within_aave"]))
        ws3.cell(r, 13, _round(row["bi_betw_match"]))
        ws3.cell(r, 14, _round(row["bi_betw_all"]))
    auto_width(ws3)

    # ── Sheet 4: Summary ─────────────────────────────────────────────────
    ws4 = wb.create_sheet("Summary")
    sum_data = [
        ("Metric",                                          "Value"),
        ("Prompts analyzed",                                summary["n_prompts"]),
        ("Trials per prompt",                               summary["n_trials"]),
        ("Model",                                           "gpt-4.1 (no system prompt)"),
        ("Embedding model",                                 EMBED_MODEL),
        ("Source",                                          DATA_PATH.name),
        ("",                                                ""),
        ("--- Cosine Similarity (semantic) ---",            ""),
        ("Within SAE mean",                                 _round(summary["cos_within_sae"])),
        ("Within AAVE mean",                                _round(summary["cos_within_aave"])),
        ("Between matched mean",                            _round(summary["cos_betw_match"])),
        ("Between all-pairs mean",                          _round(summary["cos_betw_all"])),
        ("Dialect gap (within_sae - between_matched)",      _round(summary["cos_gap"])),
        ("",                                                ""),
        ("--- Token Jaccard (lexical, embedding-free) ---", ""),
        ("Within SAE mean",                                 _round(summary["tok_within_sae"])),
        ("Within AAVE mean",                                _round(summary["tok_within_aave"])),
        ("Between matched mean",                            _round(summary["tok_betw_match"])),
        ("Between all-pairs mean",                          _round(summary["tok_betw_all"])),
        ("Dialect gap (within_sae - between_matched)",      _round(summary["tok_gap"])),
        ("",                                                ""),
        ("--- Bigram Jaccard (lexical, embedding-free) ---",""),
        ("Within SAE mean",                                 _round(summary["bi_within_sae"])),
        ("Within AAVE mean",                                _round(summary["bi_within_aave"])),
        ("Between matched mean",                            _round(summary["bi_betw_match"])),
        ("Between all-pairs mean",                          _round(summary["bi_betw_all"])),
        ("Dialect gap (within_sae - between_matched)",      _round(summary["bi_gap"])),
        ("",                                                ""),
        ("--- Statistical Test ---",                         ""),
        ("Test",                                            f"Permutation test ({summary['n_permutations']:,} shuffles), one-sided (within > between)"),
        ("Pooled within-dialect pairs",                     summary["n_within_pairs"]),
        ("Pooled between-dialect pairs",                    summary["n_between_pairs"]),
        ("Cosine observed gap",                             _round(summary["cos_gap"])),
        ("Cosine p-value",                                  _round(summary["cos_p"])),
        ("Token Jaccard observed gap",                      _round(summary["tok_gap"])),
        ("Token Jaccard p-value",                           _round(summary["tok_p"])),
        ("Bigram Jaccard observed gap",                     _round(summary["bi_gap"])),
        ("Bigram Jaccard p-value",                          _round(summary["bi_p"])),
        ("",                                                ""),
        ("--- Interpretation ---",                          ""),
        ("Significance threshold",                          "p < 0.05"),
        ("Claim",                                           "p < 0.05 on both cosine and Jaccard = two independent measures confirm dialect drives differences beyond temperature noise"),
    ]
    for r, (label, value) in enumerate(sum_data, start=1):
        lc = ws4.cell(r, 1, label)
        ws4.cell(r, 2, value)
        if str(label).startswith("---"):
            lc.fill = SECTION_FILL
            lc.font = SECTION_FONT
        elif r == 1:
            style_header(ws4.cell(r, 1))
            style_header(ws4.cell(r, 2))
    auto_width(ws4)

    wb.save(path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not DATA_PATH.exists():
        raise SystemExit(
            f"Data file not found: {DATA_PATH}\n"
            "Run collect_round1_repeated_runs.py first to generate it."
        )

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("Error: OPENAI_API_KEY environment variable is not set.")

    client  = OpenAI(api_key=api_key)
    records = load_records(DATA_PATH)
    n_prompts = len(set(r["prompt_index"] for r in records))
    n_trials  = max(r["trial"] for r in records)
    print(f"Loaded {len(records)} records — {n_prompts} prompts × 2 dialects × {n_trials} trials")

    # Attach Jaccard fields (no API needed)
    attach_jaccard_fields(records)

    # Embed for cosine similarity
    print(f"\nEmbedding {len(records)} responses with {EMBED_MODEL}...")
    vectors = get_embeddings(client, [r["response_text"] for r in records])
    for record, vec in zip(records, vectors):
        record["embedding"] = vec

    prompt_rows   = analyse(records)
    category_rows = build_category_rows(prompt_rows)
    summary       = build_summary(prompt_rows)

    # ── Print cosine table ───────────────────────────────────────────────
    print()
    print("PER-PROMPT RESULTS — COSINE SIMILARITY")
    print_table(
        ["ID", "Category", "Within SAE", "Within AAVE", "Betw Match", "Betw All"],
        [[r["prompt_index"], r["category"],
          fmt(r["cos_within_sae"]), fmt(r["cos_within_aave"]),
          fmt(r["cos_betw_match"]), fmt(r["cos_betw_all"])]
         for r in prompt_rows],
        [4, 12, 11, 12, 11, 10],
    )

    # ── Print token Jaccard table ────────────────────────────────────────
    print()
    print("PER-PROMPT RESULTS — TOKEN JACCARD")
    print_table(
        ["ID", "Category", "Within SAE", "Within AAVE", "Betw Match", "Betw All"],
        [[r["prompt_index"], r["category"],
          fmt(r["tok_within_sae"]), fmt(r["tok_within_aave"]),
          fmt(r["tok_betw_match"]), fmt(r["tok_betw_all"])]
         for r in prompt_rows],
        [4, 12, 11, 12, 11, 10],
    )

    # ── Print bigram Jaccard table ───────────────────────────────────────
    print()
    print("PER-PROMPT RESULTS — BIGRAM JACCARD")
    print_table(
        ["ID", "Category", "Within SAE", "Within AAVE", "Betw Match", "Betw All"],
        [[r["prompt_index"], r["category"],
          fmt(r["bi_within_sae"]), fmt(r["bi_within_aave"]),
          fmt(r["bi_betw_match"]), fmt(r["bi_betw_all"])]
         for r in prompt_rows],
        [4, 12, 11, 12, 11, 10],
    )

    # ── Print category breakdown ─────────────────────────────────────────
    print()
    print("BY CATEGORY — COSINE")
    print_table(
        ["Category", "n", "Within SAE", "Within AAVE", "Betw Match", "Betw All"],
        [[r["category"], r["n"],
          fmt(r["cos_within_sae"]), fmt(r["cos_within_aave"]),
          fmt(r["cos_betw_match"]), fmt(r["cos_betw_all"])]
         for r in category_rows],
        [12, 4, 11, 12, 11, 10],
    )

    print()
    print("BY CATEGORY — TOKEN JACCARD")
    print_table(
        ["Category", "n", "Within SAE", "Within AAVE", "Betw Match", "Betw All"],
        [[r["category"], r["n"],
          fmt(r["tok_within_sae"]), fmt(r["tok_within_aave"]),
          fmt(r["tok_betw_match"]), fmt(r["tok_betw_all"])]
         for r in category_rows],
        [12, 4, 11, 12, 11, 10],
    )

    # ── Print overall summary ────────────────────────────────────────────
    print()
    print("OVERALL SUMMARY")
    print(f"  Permutation test ({summary['n_permutations']:,} shuffles) — one-sided: within > between")
    print(f"  Pooled pairs — within: {summary['n_within_pairs']}, between: {summary['n_between_pairs']}")
    print_table(
        ["Metric", "Within SAE", "Within AAVE", "Betw Match", "Gap", "p-value"],
        [
            ["Cosine",   fmt(summary["cos_within_sae"]), fmt(summary["cos_within_aave"]),
             fmt(summary["cos_betw_match"]), fmt(summary["cos_gap"]), fmt(summary["cos_p"])],
            ["Token J",  fmt(summary["tok_within_sae"]), fmt(summary["tok_within_aave"]),
             fmt(summary["tok_betw_match"]), fmt(summary["tok_gap"]), fmt(summary["tok_p"])],
            ["Bigram J", fmt(summary["bi_within_sae"]),  fmt(summary["bi_within_aave"]),
             fmt(summary["bi_betw_match"]),  fmt(summary["bi_gap"]),  fmt(summary["bi_p"])],
        ],
        [10, 11, 12, 11, 8, 10],
    )

    print()
    for label, p in [("Cosine", summary["cos_p"]), ("Token J", summary["tok_p"]), ("Bigram J", summary["bi_p"])]:
        if p is not None:
            sig = "p < 0.05 — significant" if p < 0.05 else "p ≥ 0.05 — not significant"
            print(f"  {label}: p = {fmt(p)} — {sig}")

    write_xlsx(OUTPUT_PATH, prompt_rows, category_rows, summary)
    print(f"\nResults saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
